spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:iac
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: #naver id
    password: #naver password
    properties:
      mail:
        smtp:
          ssl:
            enable: true

server:
  port: 8061